from fpdf import FPDF
from datetime import date
import os

SENT_COLORS = {
    "Positive": (15, 110, 86),
    "Negative": (113, 43,  19),
    "Neutral":  (133, 79,  11),
}

PILLAR_COLORS = {
    "Overall":       (29, 158, 117),
    "Environmental": (29, 158, 117),
    "Social":        (127, 119, 221),
    "Governance":    (196, 125,  14),
}


def generate_pdf(company: str, scores: dict,
                 brief: str, articles: list) -> str:

    pdf = FPDF("P", "mm", "A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Green header bar ────────────────────────
    pdf.set_fill_color(29, 158, 117)
    pdf.rect(0, 0, 210, 30, "F")
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(10, 7)
    pdf.cell(0, 9, "ESG Intelligence Report", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_xy(10, 18)
    pdf.cell(0, 6, f"Company: {company}   |   Date: {date.today()}   |   Powered by AI")

    # ── ESG Scores section ───────────────────────
    pdf.set_xy(10, 38)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 8, "ESG Sentiment Scores", ln=True)
    pdf.ln(2)

    for pillar, score in scores.items():
        r, g, b = PILLAR_COLORS.get(pillar, (100, 100, 100))

        # Pillar label
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(52, 9, f"  {pillar}", 0, 0, "L", fill=True)

        # Grey background bar
        x = pdf.get_x()
        y = pdf.get_y()
        pdf.set_fill_color(220, 220, 220)
        pdf.cell(100, 9, "", 0, 0, fill=True)

        # Colored progress bar
        bar_width = int(score * 1.0)
        pdf.set_fill_color(r, g, b)
        pdf.set_xy(x, y)
        pdf.cell(bar_width, 9, "", 0, 0, fill=True)

        # Score label
        pdf.set_xy(x + 102, y)
        pdf.set_text_color(40, 40, 40)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(20, 9, f"{score}/100", 0, 1)
        pdf.ln(1)

    # ── AI Brief section ─────────────────────────
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 8, "AI Intelligence Brief", ln=True)
    pdf.ln(2)
    pdf.set_fill_color(235, 248, 243)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(0, 6, brief, border=0, fill=True)

    # ── Articles section ─────────────────────────
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 8, "Analyzed News Articles", ln=True)
    pdf.ln(2)

    for a in articles[:10]:
        sent = a.get("sentiment", "Neutral")
        r, g, b = SENT_COLORS.get(sent, (80, 80, 80))

        # Sentiment badge
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(24, 6, f"  {sent}", 0, 0, fill=True)

        # Article title
        pdf.set_text_color(40, 40, 40)
        pdf.set_font("Helvetica", "", 9)
        title = a["title"][:72] + ("..." if len(a["title"]) > 72 else "")
        pdf.cell(0, 6, f"  {title}", ln=True)

        # Risk flag
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(110, 110, 110)
        flag = a.get("risk_flag", "")[:90]
        pdf.cell(0, 5, f"     {a.get('pillar','')} · {a.get('source','')} · {flag}", ln=True)
        pdf.ln(1)

    # ── Footer ───────────────────────────────────
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10,
             f"Generated by ESG Intelligence Tracker | {date.today()} | Confidential",
             0, 0, "C")

    os.makedirs("reports", exist_ok=True)
    path = f"reports/{company.replace(' ','_')}_ESG_{date.today()}.pdf"
    pdf.output(path)
    return path